### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by ASTeterin** [R4DEONN/pizza_hot#10]
Методы выглядят одинаково. Так и должно быть?
https://github.com/R4DEONN/pizza_hot/blob/bdc68d539008bab47fa8bebe17e269f04c4d8e0e/src/Security/UserProvider.php#LL21C1-L39C6

**Comment by R4DEONN** [comment]
Удалил метод loadUserByIdentifier(), оказалось, что в UserProvider достаточно объявить только loadUserByUsername()
