### ISSUE TITLE
Предложение 1

### ISSUE THREAD

**Issue by ASTeterin** [R4DEONN/pizza_hot#3]
Лучше вместо $admin сделать свойство $role, тип int. При этом необходимо будет поменять и в доктриновской модели, и в таблице. Тогда система будет более гибкой. 
https://github.com/R4DEONN/pizza_hot/blob/58dd303b1c89a2bbe700f4a7833bdbb50733f593/src/Entity/User.php#L15

**Comment by R4DEONN** [comment]
Изменил
