### ISSUE TITLE
Предложение 1

### ISSUE THREAD

**Issue by ASTeterin** [R4DEONN/pizza_hot#4]
Можно подумать над названием метода. Сейчас название подразумевает, что возвращаемый загружает изображения и ничего не возвращает.
https://github.com/R4DEONN/pizza_hot/blob/bdc68d539008bab47fa8bebe17e269f04c4d8e0e/src/Service/ImageService.php#LL18C21-L18C39

**Comment by R4DEONN** [comment]
Исправил название на moveImageToUploadsAndGetPath
