### ISSUE TITLE
замечание 2

### ISSUE THREAD

**Issue by ASTeterin** [R4DEONN/pizza_hot#6]
Можно указать тип возвращаемого значения с использованием phpDoc, т.к не понятно массив чего должен возвращаться. В ProductServiceInterface тоже https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.return.pkg.html
https://github.com/R4DEONN/pizza_hot/blob/bdc68d539008bab47fa8bebe17e269f04c4d8e0e/src/Service/OrderServiceInterface.php#LL8C1-L8C60

**Comment by R4DEONN** [comment]
Исправил
